### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by m9dfukc** [caribou/caribou#6]
Hey,

I really like the concept caribou and was about to build a website with it ... unfortunately this seems to be depreciated?!

Can you give some insights onto the future roadmap?

**Comment by noisesmith** [comment]
It's no longer a sponsored project, but a few of us still use it. Development has tapered off, but not fully stopped.

I have some work in progress for plugin features (eventually subsuming the admin interface as an optional plugin), and there is also work done toward datomic support that could be finished and integrated. But yes, the rate of development has slowed.

Contributions, bug reports, questions, and suggestions are welcome.

**Comment by prismofeverything** [comment]
Andreas,

Caribou will always be a project dear to my heart.  Several sites have been
built with it so it has been battle tested and is in a pretty functional
state.  The documentation is also pretty thorough:
http://caribou.github.io/caribou/docs/outline.html

Let us know if you have any questions.

**Comment by m9dfukc** [comment]
@prismofeverything, yes the documentation is pretty indeed!

I like the concept and especially the admin of caribou. It's a pity that weareinstrument has switched over to squarespace. I will follow the progress of caribou closely ... unfortunately my customer already made the decision for craftcms (php arg).

Looking forward to the upcoming plugin features.
